[ruff]
select = ["E", "F", "W", "C90"]
ignore = ["E501"]
extend-exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "*egg-info",
    ".venv",
    "venv",
    ".tox",
]
line-length = 88
target-version = "py311"