"""Generate a 16-color tcod terminal palette from design_tokens.json.

Step 11 of Proposal 5 (Visual Style Unification).

Reads colors from the single source of truth (design_tokens.json) and emits a
Python list of RGB tuples suitable for tcod rendering. Run:

    python tools/generate_palette.py > core/palette_generated.py
"""
import json
import os


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert #rrggbb to (r, g, b)."""
    h = hex_color.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def build_palette(tokens: dict) -> list[tuple[int, int, int]]:
    color = tokens.get("color", {})
    semantic = color.get("semantic", {})
    tiles = color.get("tiles", {})

    def pick(*keys, default="#000000"):
        node = semantic
        for k in keys:
            if isinstance(node, dict) and k in node:
                node = node[k]
            else:
                return default
        return node if isinstance(node, str) else default

    bg = pick("background", "primary", default="#ffffff")
    text = pick("text", "primary", default="#1f2937")
    danger = pick("danger", default="#dc2626")
    success = pick("success", default="#16a34a")
    warning = pick("warning", default="#d97706")
    info = pick("info", default="#2563eb")

    wall = tiles.get("wall", "#2c3e50")
    floor = tiles.get("floor", "#1c2230")
    water = tiles.get("water", "#2980b9")
    player = tiles.get("player", "#ecf0f1")
    enemy = tiles.get("enemy", "#e74c3c")
    pet = tiles.get("pet", "#f8b500")
    accent = tiles.get("accent", "#d4af37")

    palette = [
        hex_to_rgb(bg),        # 0: background
        hex_to_rgb(text),      # 1: foreground/text
        hex_to_rgb(wall),      # 2: wall
        hex_to_rgb(floor),     # 3: floor
        hex_to_rgb(water),     # 4: water
        hex_to_rgb(player),    # 5: player
        hex_to_rgb(enemy),     # 6: enemy
        hex_to_rgb(pet),       # 7: pet
        hex_to_rgb(accent),    # 8: accent
        hex_to_rgb(danger),    # 9: danger/damage
        hex_to_rgb(success),   # 10: success/heal
        hex_to_rgb(warning),   # 11: warning
        (139, 155, 180),       # 12: gray scale
        (107, 123, 148),       # 13
        (75, 91, 116),         # 14
        (44, 62, 80),          # 15
    ]
    return palette


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    with open(os.path.join(root, "design_tokens.json"), encoding="utf-8") as f:
        tokens = json.load(f)

    palette = build_palette(tokens)
    print("# Generated by tools/generate_palette.py - do not edit by hand")
    print("PALETTE_16 = [")
    for i, (r, g, b) in enumerate(palette):
        print(f"    ({r}, {g}, {b}),  # {i}")
    print("]")


if __name__ == "__main__":
    main()
